environment:
  nodejs_version: 12

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm install

test_script:
  - node --version
  - npm --version
  - appveyor-retry npm test
  - appveyor-retry npm run build

build: off
shallow_clone: true

